version: '3.8'

networks:
  default:
    name: ${APPLICATION_DOMAIN}
    driver: bridge

services:

  cloud-media-server:
    image: ${DOCKER_REGISTRY-}mrcp-api:${PRODUCT_VERSION-}
    restart: ${RESTART_POLICY-unless-stopped}
    environment:
      MEDIA_SERVER__ALLOW_DEPLOYMENT_OVERRIDE: "${MEDIA_SERVER__ALLOW_DEPLOYMENT_OVERRIDE}"
      MEDIA_SERVER__ALLOW_OPERATOR_OVERRIDE: "${MEDIA_SERVER__ALLOW_OPERATOR_OVERRIDE}"
      MEDIA_SERVER__DEFAULT_DEPLOYMENT_ID: "${MEDIA_SERVER__DEFAULT_DEPLOYMENT_ID}"
      MEDIA_SERVER__DEFAULT_OPERATOR_ID: "${MEDIA_SERVER__DEFAULT_OPERATOR_ID}"
      MEDIA_SERVER__NUM_CHANNELS: "${MEDIA_SERVER__NUM_CHANNELS}"
      MEDIA_SERVER__SERVER_IP: "${MEDIA_SERVER__SERVER_IP}"
      MEDIA_SERVER__LUMENVOX_API_ADDRESS: "${MEDIA_SERVER__LUMENVOX_API_ADDRESS}"
      MEDIA_SERVER__LUMENVOX_API_PORT: "${MEDIA_SERVER__LUMENVOX_API_PORT}"
      MEDIA_SERVER__USE_TLS: "${MEDIA_SERVER__USE_TLS}"
      MEDIA_SERVER__EXTRA_ROOT_CA: "${MEDIA_SERVER__EXTRA_ROOT_CA}"
    ports:
      - "554:554/tcp"
      - "5060-5061:5060-5061/tcp"
      - "5060-5061:5060-5061/udp"
      - "20000-20200:20000-20200/tcp"
      - "25000-25200:25000-25200/udp"
    volumes:
      - ./certs:/certs
    extra_hosts:
      - "${MEDIA_SERVER__HOST_MAP:-placeholder:127.0.0.1}"
    network_mode: host
