version: '3.8'

networks:
  default:
    name: ${APPLICATION_DOMAIN}
    driver: bridge

services:

  cloud-media-server:
    image: ${DOCKER_REGISTRY-}mrcp-api:${PRODUCT_VERSION-}
    restart: ${RESTART_POLICY-unless-stopped}
    environment:
      MEDIA_SERVER__ALLOW_DEPLOYMENT_OVERRIDE: "${MEDIA_SERVER__ALLOW_DEPLOYMENT_OVERRIDE}"
      MEDIA_SERVER__ALLOW_OPERATOR_OVERRIDE: "${MEDIA_SERVER__ALLOW_OPERATOR_OVERRIDE}"
      MEDIA_SERVER__DEFAULT_DEPLOYMENT_ID: "${MEDIA_SERVER__DEFAULT_DEPLOYMENT_ID}"
      MEDIA_SERVER__DEFAULT_OPERATOR_ID: "${MEDIA_SERVER__DEFAULT_OPERATOR_ID}"
      MEDIA_SERVER__SPEECH_API_ADDRESS: "${MEDIA_SERVER__SPEECH_API_ADDRESS}"
      MEDIA_SERVER__SPEECH_API_PORT: "${MEDIA_SERVER__SPEECH_API_PORT}"
      MEDIA_SERVER__USE_TLS: "${MEDIA_SERVER__USE_TLS}"
    ports:
      - "554:554/tcp"
      - "5060-5061:5060-5061/tcp"
      - "5060-5061:5060-5061/udp"
      - "20000-20500:20000-20500/tcp"
      - "25000-25500:25000-25500/udp"
    volumes:
      - ./certs:/certs
    extra_hosts:
      - "${MEDIA_SERVER__HOST_MAP:-placeholder:127.0.0.1}"
